CREATE OR REPLACE TRIGGER SALVAR_LOG_PRODUTO_PRECO
BEFORE DELETE ON PRODUTO_PRECO 
FOR EACH ROW
BEGIN
    INSERT INTO PRODUTO_LOG (ID, CAMPO, VALOR, NOME_TABELA)
    VALUES(:OLD.ID, 'ID_PRODUTO', :OLD.ID_PRODUTO, 'PRODUTO_PRECO');
    INSERT INTO PRODUTO_LOG (ID, CAMPO, VALOR, NOME_TABELA)
    VALUES(:OLD.ID, 'VALOR', :OLD.VALOR, 'PRODUTO_PRECO');
    INSERT INTO PRODUTO_LOG (ID, CAMPO, VALOR, NOME_TABELA)
    VALUES(:OLD.ID, 'STATUS', :OLD.STATUS, 'PRODUTO_PRECO');
    INSERT INTO PRODUTO_LOG (ID, CAMPO, VALOR, NOME_TABELA)
    VALUES(:OLD.ID, 'CADASTRO', :OLD.CADASTRO, 'PRODUTO_PRECO');
END;

DELETE FROM PRODUTO_PRECO WHERE ID = 17;