CREATE OR REPLACE FUNCTION CALCULA_DESCONTO(P_ID PRODUTO.ID%TYPE, P_APLICAR_DESCONTO NUMBER) RETURN NUMBER IS 
    V_VALOR NUMBER;
BEGIN
    SELECT PP.VALOR INTO V_VALOR 
    FROM PRODUTO P,
         PRODUTO_PRECO PP
    WHERE P.ID = P_ID
    AND P.ID = PP.ID_PRODUTO
    AND PP.STATUS = 1;
    
    IF P_APLICAR_DESCONTO = 1 THEN
        RETURN V_VALOR - (V_VALOR*0.1);
    END IF;
END;

SELECT CALCULA_DESCONTO(1, 1) AS VALOR_DESCONTO FROM DUAL;