CREATE OR REPLACE TRIGGER SALVAR_LOG
AFTER UPDATE ON PRODUTO 
FOR EACH ROW

BEGIN
    INSERT INTO PRODUTO_LOG (ID, CAMPO, VALOR, NOME_TABELA)
    VALUES(:NEW.ID, 'DESRICAO', :NEW.DESCRICAO, 'PRODUTO');
    INSERT INTO PRODUTO_LOG (ID, CAMPO, VALOR, NOME_TABELA)
    VALUES(:NEW.ID, 'STATUS', :NEW.STATUS, 'PRODUTO');
    INSERT INTO PRODUTO_LOG (ID, CAMPO, VALOR, NOME_TABELA)
    VALUES(:NEW.ID, 'CADASTRO', :NEW.CADASTRO, 'PRODUTO');
    INSERT INTO PRODUTO_LOG (ID, CAMPO, VALOR, NOME_TABELA)
    VALUES(:NEW.ID, 'QUANTIDADE_EM_ESTOQUE', :NEW.QUANTIDADE_EM_ESTOQUE, 'PRODUTO');
END;

UPDATE PRODUTO
SET DESCRICAO = 'PRODUTO 3 NOVO'
WHERE ID = 3;